# Canonical nutritional database of foods (synchronized with frontend commonFoods.js and ScouterModal)

FOOD_DATABASE = {
    # Custom / Indian / DBZ themed foods from ScouterModal
    "Paneer Curry": {"cals": 420, "protein": 18, "carbs": 12, "fat": 34, "unit": "g", "amount": 200, "ingredients": "Cottage cheese, tomatoes, butter, cream, spices."},
    "Paneer Butter Masala": {"cals": 420, "protein": 18, "carbs": 12, "fat": 34, "unit": "g", "amount": 200, "ingredients": "Cottage cheese, heavy cream, tomato puree, butter, traditional Indian spices."},
    "Dal Makhani": {"cals": 350, "protein": 12, "carbs": 45, "fat": 14, "unit": "g", "amount": 200, "ingredients": "Slow-cooked black lentils and kidney beans, cream, butter, ginger."},
    "Masala Dosa": {"cals": 350, "protein": 7, "carbs": 62, "fat": 8, "unit": "g", "amount": 150, "ingredients": "Thin fermented rice crepe filled with spiced potato mash, served with chutney."},
    "Samosa (2 pcs)": {"cals": 308, "protein": 5, "carbs": 36, "fat": 16, "unit": "g", "amount": 100, "ingredients": "Crispy fried pastry pockets stuffed with seasoned potatoes and green peas."},
    "Chicken Curry": {"cals": 380, "protein": 30, "carbs": 8, "fat": 24, "unit": "g", "amount": 250, "ingredients": "Chicken pieces simmered in an aromatic onion, tomato, and spice gravy."},
    "Chicken Tikka Masala": {"cals": 450, "protein": 35, "carbs": 10, "fat": 28, "unit": "g", "amount": 250, "ingredients": "Grilled marinated chicken chunks cooked in a spicy, creamy spiced tomato sauce."},
    "Egg Bhurji (Scrambled)": {"cals": 260, "protein": 16, "carbs": 4, "fat": 18, "unit": "g", "amount": 150, "ingredients": "Scrambled eggs stir-fried with chopped onions, green chilies, tomatoes, and spices."},
    "Whole Wheat Roti / Chapati": {"cals": 104, "protein": 3, "carbs": 22, "fat": 0.5, "unit": "g", "amount": 40, "ingredients": "Traditional Indian flatbread made of whole wheat flour, roasted on a tawa."},
    "Butter Naan": {"cals": 260, "protein": 8, "carbs": 45, "fat": 5, "unit": "g", "amount": 100, "ingredients": "Leavened oven-baked flatbread brushed with melted butter."},
    "Vegetable Biryani": {"cals": 480, "protein": 12, "carbs": 78, "fat": 14, "unit": "g", "amount": 300, "ingredients": "Aromatic basmati rice layered with mixed vegetables, herbs, and spices."},
    "Senzu Bean Energy Salad": {"cals": 320, "protein": 18, "carbs": 45, "fat": 8, "unit": "g", "amount": 250, "ingredients": "Senzu bean extract, baby spinach, kale, cooked quinoa, cherry tomatoes, olive oil."},
    "Vegeta's Pride Shake": {"cals": 450, "protein": 40, "carbs": 35, "fat": 10, "unit": "ml", "amount": 400, "ingredients": "Whey protein isolate, banana, creamy peanut butter, unsweetened almond milk."},
    "Piccolo's Hyperbolic Oats": {"cals": 380, "protein": 15, "carbs": 65, "fat": 7, "unit": "g", "amount": 250, "ingredients": "Rolled oats, organic chia seeds, wild fresh blueberries, natural honey."},
    "Chichi's Roasted Chicken": {"cals": 580, "protein": 50, "carbs": 12, "fat": 32, "unit": "g", "amount": 350, "ingredients": "Herb-marinated free-range chicken breast, slow-roasted with garlic."},
    "Saiyan Fried Rice": {"cals": 520, "protein": 14, "carbs": 85, "fat": 12, "unit": "g", "amount": 300, "ingredients": "Stir-fried basmati rice, carrots, green peas, spring onion, eggs, soy sauce."},

    # Common Foods from commonFoods.js
    "White Bread": {"cals": 75, "protein": 2, "carbs": 14, "fat": 1, "unit": "slice", "amount": 1},
    "Whole Wheat Bread": {"cals": 81, "protein": 4, "carbs": 14, "fat": 1, "unit": "slice", "amount": 1},
    "Brown Bread": {"cals": 75, "protein": 3, "carbs": 12, "fat": 1, "unit": "slice", "amount": 1},
    "Multigrain Bread": {"cals": 85, "protein": 4, "carbs": 15, "fat": 1.5, "unit": "slice", "amount": 1},
    "Chapati / Roti": {"cals": 104, "protein": 3, "carbs": 22, "fat": 0.5, "unit": "medium (6 inch)", "amount": 1},
    "Naan (Plain)": {"cals": 260, "protein": 8, "carbs": 45, "fat": 5, "unit": "medium", "amount": 1},
    "Bagel": {"cals": 250, "protein": 10, "carbs": 49, "fat": 1.5, "unit": "medium", "amount": 1},
    "Croissant": {"cals": 231, "protein": 5, "carbs": 26, "fat": 12, "unit": "medium", "amount": 1},

    "Milk (Whole)": {"cals": 149, "protein": 8, "carbs": 12, "fat": 8, "unit": "cup", "amount": 1},
    "Milk (Skim/Low fat)": {"cals": 83, "protein": 8, "carbs": 12, "fat": 0.2, "unit": "cup", "amount": 1},
    "Milk (Almond)": {"cals": 30, "protein": 1, "carbs": 1, "fat": 2.5, "unit": "cup", "amount": 1},
    "Milk (Soy)": {"cals": 80, "protein": 7, "carbs": 4, "fat": 4, "unit": "cup", "amount": 1},
    "Greek Yogurt (Plain)": {"cals": 100, "protein": 17, "carbs": 6, "fat": 0.7, "unit": "cup", "amount": 1},
    "Yogurt (Fruit)": {"cals": 150, "protein": 5, "carbs": 25, "fat": 2, "unit": "cup", "amount": 1},
    "Butter": {"cals": 102, "protein": 0.1, "carbs": 0, "fat": 11.5, "unit": "tbsp", "amount": 1},
    "Cheese (Cheddar)": {"cals": 113, "protein": 7, "carbs": 0.4, "fat": 9, "unit": "slice", "amount": 1},
    "Cottage Cheese (Paneer)": {"cals": 222, "protein": 25, "carbs": 8, "fat": 10, "unit": "cup", "amount": 1},
    "Cream Cheese": {"cals": 99, "protein": 2, "carbs": 1, "fat": 10, "unit": "tbsp", "amount": 2},

    "Egg (Boiled)": {"cals": 78, "protein": 6, "carbs": 0.6, "fat": 5, "unit": "large", "amount": 1},
    "Egg (Fried)": {"cals": 90, "protein": 6, "carbs": 0.6, "fat": 7, "unit": "large", "amount": 1},
    "Egg (Scrambled)": {"cals": 91, "protein": 6, "carbs": 1, "fat": 7, "unit": "large", "amount": 1},
    "Oats (Rolled)": {"cals": 150, "protein": 5, "carbs": 27, "fat": 2.5, "unit": "cup (dry)", "amount": 0.5},
    "Corn Flakes": {"cals": 100, "protein": 2, "carbs": 24, "fat": 0, "unit": "cup", "amount": 1},
    "Muesli": {"cals": 290, "protein": 8, "carbs": 66, "fat": 4, "unit": "cup", "amount": 1},
    "Pancakes": {"cals": 175, "protein": 5, "carbs": 20, "fat": 7, "unit": "medium", "amount": 2},

    "Chicken Breast (Cooked)": {"cals": 165, "protein": 31, "carbs": 0, "fat": 3.6, "unit": "g", "amount": 100},
    "Chicken Thigh (Cooked)": {"cals": 209, "protein": 26, "carbs": 0, "fat": 10.9, "unit": "g", "amount": 100},
    "Salmon (Cooked)": {"cals": 206, "protein": 22, "carbs": 0, "fat": 12, "unit": "g", "amount": 100},
    "Tuna (Canned)": {"cals": 132, "protein": 29, "carbs": 0, "fat": 1, "unit": "can", "amount": 1},
    "Beef Stake (Cooked)": {"cals": 271, "protein": 26, "carbs": 0, "fat": 19, "unit": "g", "amount": 100},
    "Ground Beef (Lean)": {"cals": 250, "protein": 26, "carbs": 0, "fat": 15, "unit": "g", "amount": 100},
    "Tofu": {"cals": 76, "protein": 8, "carbs": 2, "fat": 4.8, "unit": "g", "amount": 100},
    "Lentils (Dal, Cooked)": {"cals": 230, "protein": 18, "carbs": 40, "fat": 0.8, "unit": "cup", "amount": 1},
    "Chickpeas (Cooked)": {"cals": 269, "protein": 14.5, "carbs": 45, "fat": 4.2, "unit": "cup", "amount": 1},
    "Protein Powder (Whey)": {"cals": 120, "protein": 24, "carbs": 3, "fat": 1.5, "unit": "scoop", "amount": 1},

    "Rice (White, Cooked)": {"cals": 130, "protein": 2.7, "carbs": 28, "fat": 0.3, "unit": "g", "amount": 100},
    "Rice (Brown, Cooked)": {"cals": 112, "protein": 2.6, "carbs": 24, "fat": 0.9, "unit": "g", "amount": 100},
    "Basmati Rice": {"cals": 121, "protein": 3.5, "carbs": 25, "fat": 0.4, "unit": "g", "amount": 100},
    "Pasta (Cooked)": {"cals": 158, "protein": 6, "carbs": 31, "fat": 0.9, "unit": "g", "amount": 100},
    "Quinoa (Cooked)": {"cals": 120, "protein": 4.4, "carbs": 21, "fat": 1.9, "unit": "g", "amount": 100},
    "Tortilla (Flour)": {"cals": 140, "protein": 4, "carbs": 24, "fat": 3.5, "unit": "medium", "amount": 1},

    "Apple": {"cals": 95, "protein": 0.5, "carbs": 25, "fat": 0.3, "unit": "medium", "amount": 1},
    "Banana": {"cals": 105, "protein": 1.3, "carbs": 27, "fat": 0.4, "unit": "medium", "amount": 1},
    "Orange": {"cals": 62, "protein": 1.2, "carbs": 15, "fat": 0.2, "unit": "medium", "amount": 1},
    "Strawberries": {"cals": 49, "protein": 1, "carbs": 12, "fat": 0.5, "unit": "cup", "amount": 1},
    "Blueberries": {"cals": 84, "protein": 1, "carbs": 21, "fat": 0.5, "unit": "cup", "amount": 1},
    "Grapes": {"cals": 104, "protein": 1, "carbs": 27, "fat": 0.2, "unit": "cup", "amount": 1},
    "Watermelon": {"cals": 46, "protein": 1, "carbs": 12, "fat": 0.2, "unit": "cup (diced)", "amount": 1},
    "Pineapple": {"cals": 82, "protein": 1, "carbs": 22, "fat": 0.2, "unit": "cup", "amount": 1},
    "Mango": {"cals": 202, "protein": 3, "carbs": 50, "fat": 1, "unit": "medium", "amount": 1},
    "Avocado": {"cals": 234, "protein": 3, "carbs": 12, "fat": 21, "unit": "medium", "amount": 1},
    "Lemon": {"cals": 17, "protein": 0.6, "carbs": 5, "fat": 0.2, "unit": "fruit", "amount": 1},

    "Broccoli": {"cals": 55, "protein": 3.7, "carbs": 11, "fat": 0.6, "unit": "cup (chopped)", "amount": 1},
    "Spinach": {"cals": 7, "protein": 1, "carbs": 1, "fat": 0, "unit": "cup (raw)", "amount": 1},
    "Carrot": {"cals": 25, "protein": 0.6, "carbs": 6, "fat": 0.1, "unit": "medium", "amount": 1},
    "Potato (Boiled)": {"cals": 87, "protein": 1.9, "carbs": 20, "fat": 0.1, "unit": "g", "amount": 100},
    "Potato (Fried/Chips)": {"cals": 312, "protein": 3.4, "carbs": 41, "fat": 15, "unit": "g", "amount": 100},
    "Sweet Potato": {"cals": 112, "protein": 2, "carbs": 26, "fat": 0.1, "unit": "medium", "amount": 1},
    "Tomato": {"cals": 22, "protein": 1, "carbs": 5, "fat": 0.2, "unit": "medium", "amount": 1},
    "Onion": {"cals": 44, "protein": 1, "carbs": 10, "fat": 0.1, "unit": "medium", "amount": 1},
    "Cucumber": {"cals": 8, "protein": 0.3, "carbs": 2, "fat": 0.1, "unit": "cup", "amount": 0.5},
    "Bell Pepper": {"cals": 24, "protein": 1, "carbs": 6, "fat": 0.2, "unit": "medium", "amount": 1},
    "Mushrooms": {"cals": 15, "protein": 2.2, "carbs": 2.3, "fat": 0.2, "unit": "cup", "amount": 1},

    "Almonds": {"cals": 164, "protein": 6, "carbs": 6, "fat": 14, "unit": "oz", "amount": 1},
    "Walnuts": {"cals": 185, "protein": 4, "carbs": 4, "fat": 18, "unit": "oz", "amount": 1},
    "Chia Seeds": {"cals": 138, "protein": 5, "carbs": 12, "fat": 9, "unit": "oz", "amount": 1},
    "Peanut Butter": {"cals": 190, "protein": 8, "carbs": 7, "fat": 16, "unit": "tbsp", "amount": 2},
    "Olive Oil": {"cals": 119, "protein": 0, "carbs": 0, "fat": 13.5, "unit": "tbsp", "amount": 1},

    "Water": {"cals": 0, "protein": 0, "carbs": 0, "fat": 0, "unit": "cup", "amount": 1},
    "Coffee (Black)": {"cals": 2, "protein": 0, "carbs": 0, "fat": 0, "unit": "cup", "amount": 1},
    "Tea (Black)": {"cals": 2, "protein": 0, "carbs": 0, "fat": 0, "unit": "cup", "amount": 1},
    "Tea (with Milk & Sugar)": {"cals": 45, "protein": 1, "carbs": 8, "fat": 1, "unit": "cup", "amount": 1},
    "Orange Juice": {"cals": 112, "protein": 2, "carbs": 26, "fat": 0.5, "unit": "cup", "amount": 1},
    "Cola / Soda": {"cals": 140, "protein": 0, "carbs": 39, "fat": 0, "unit": "can", "amount": 1}
}
